version: '2'
services:
  node1:
    hostname: node1
    image: jboss/keycloak-adapter-wildfly:3.4.3.Final
    environment:
    - "KEYCLOAK_LOGLEVEL=DEBUG"
    - "TZ=Europe/Paris"
    - "KEYCLOAK_HOST=api-inte03.lbg.office.fr.lyra"
    - "KEYCLOAK_REALM=myRealm"
    - "KEYCLOAK_CLIENT=testPrivate"
    - "KEYCLOAK_SECRET=421f92a0-7882-4c2c-b448-da3569d56600"
    ports:
     - "1080:8080"
     - "1990:9990"
     - "1787:8787"
    command:  ["/opt/jboss/wildfly/bin/standalone.sh","-b", "0.0.0.0"] 
    volumes:
      - /D/Developpement/archi/idm/ear/docker/clients/n1/configuration:/opt/jboss/wildfly/standalone/configuration:rw
      - /D/Developpement/archi/idm/ear/docker/clients/n1/deployments:/opt/jboss/wildfly/standalone/deployments:rw
